<?php

use App\Modelos\Marcador;
use Illuminate\Database\Seeder;

class Marcador1Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'1', 	'nivel'=>'1', 	'nombre'=>'UNIDAD 15. ENFERMEDADES QUIRURGICAS DEL SISTEMA DIGESTIVO', 	'pagina'=>'1',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'Contenido', 	'pagina'=>'2',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'I. ASPECTOS Y ANTIVIDADES DE APLICACIÓN FUNDAMENTAL', 	'pagina'=>'3',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'4', 	'nivel'=>'2', 	'nombre'=>'1. PREVENCION DE ESTILOS DE VIDA NO SALUDABLES', 	'pagina'=>'3',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'5', 	'nivel'=>'3', 	'nombre'=>'ANTECEDENTES', 	'pagina'=>'3',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'6', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS RELACIONADAS CON ESTILOS DE VIDA NO SALUDABLES', 	'pagina'=>'4',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'7', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS EN ADOLESCENTES', 	'pagina'=>'4',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'8', 	'nivel'=>'1', 	'nombre'=>'II. NORMAS DE ATENCION CLINICA', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'9', 	'nivel'=>'2', 	'nombre'=>'1. ABDOMEN AGUDO QUIRURGICO', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'10', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'11', 	'nivel'=>'3', 	'nombre'=>'ETIOLOGIA', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'12', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'13', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINIDOS: de acuerdo a etiologia', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'14', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'15', 	'nivel'=>'4', 	'nombre'=>'Laboratorioi (nivel II ó III)', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'16', 	'nivel'=>'4', 	'nombre'=>'Prueba de gaginete (nivel II ó III)', 	'pagina'=>'5',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'17', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'18', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'19', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'20', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'21', 	'nivel'=>'5', 	'nombre'=>'Nivel I', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'22', 	'nivel'=>'5', 	'nombre'=>'Tratemiento pre-referencia', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'23', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'24', 	'nivel'=>'5', 	'nombre'=>'Nivel II ó III', 	'pagina'=>'6',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'25', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO PRE QUIRURGICO', 	'pagina'=>'7',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'26', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LÍQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'7',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'27', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'8',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'28', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POSTQUIRURGICO', 	'pagina'=>'8',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'29', 	'nivel'=>'4', 	'nombre'=>'CUADRO N| 2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'8',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'30', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'9',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'31', 	'nivel'=>'3', 	'nombre'=>'CRITERIO DE REFERENCIA', 	'pagina'=>'10',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'32', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'10',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'33', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'10',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'34', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'10',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'35', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'10',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'36', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'10',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'37', 	'nivel'=>'2', 	'nombre'=>'2. APENDICITIS AGUDA NO COMPLICADA', 	'pagina'=>'11',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'38', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'11',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'39', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'11',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'40', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'11',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'41', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'12',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'42', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'12',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'43', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'12',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'44', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'12',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'45', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'12',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'46', 	'nivel'=>'5', 	'nombre'=>'Nivel I', 	'pagina'=>'12',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'47', 	'nivel'=>'5', 	'nombre'=>'Tratamiento pre-referencia', 	'pagina'=>'12',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'48', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'13',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'49', 	'nivel'=>'4', 	'nombre'=>'TRATAMIENTO PRE-QUIRURICO', 	'pagina'=>'13',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'50', 	'nivel'=>'5', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'13',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'51', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'13',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'52', 	'nivel'=>'4', 	'nombre'=>'MANEJO DEL MUÑON APENDICULAR', 	'pagina'=>'14',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'53', 	'nivel'=>'4', 	'nombre'=>'EN CASO EXCEPCIONAL CON SEVERO COMPROMISO CECAL RECURRIR A RESECCION ILEO-CECAL O HEMICOLECTOMIA DERECHA CON ILEO-COLO ANASTOMOSIS', 	'pagina'=>'14',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'54', 	'nivel'=>'3', 	'nombre'=>'TRATEMIENTO POSTQUIRURGICO INMEDIATO', 	'pagina'=>'14',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'55', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'14',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'56', 	'nivel'=>'3', 	'nombre'=>'CUIDADOS O MEDIDAS GENERALES POST OPERATORIOS', 	'pagina'=>'15',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'57', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'15',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'58', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'16',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'59', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'16',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'60', 	'nivel'=>'3', 	'nombre'=>'RECOMEDACIONES', 	'pagina'=>'16',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'61', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'16',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'62', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'16',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'63', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'16',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'64', 	'nivel'=>'2', 	'nombre'=>'3. PERITONITIS AGUDA GENERALIZADA', 	'pagina'=>'17',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'65', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'17',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'66', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'17',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'67', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'17',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'68', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'18',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'69', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'18',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'70', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'18',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'71', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'18',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'72', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'18',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'73', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'19',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'74', 	'nivel'=>'4', 	'nombre'=>'TRATAMIENTO PRE QUIRURGICO', 	'pagina'=>'19',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'75', 	'nivel'=>'5', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'19',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'76', 	'nivel'=>'4', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'20',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'77', 	'nivel'=>'4', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'20',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'78', 	'nivel'=>'5', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'21',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'79', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'22',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'80', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'22',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'81', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'22',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'82', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'22',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'83', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'23',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'84', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'23',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'85', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'23',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'86', 	'nivel'=>'2', 	'nombre'=>'4. COLECISTITIS AGUDA', 	'pagina'=>'24',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'87', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'24',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'88', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'24',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'89', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'24',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'90', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'24',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'91', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'25',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'92', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'25',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'93', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'25',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'94', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'25',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'95', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'25',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'96', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO PRE QUIRURGICO', 	'pagina'=>'25',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'97', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'26',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'98', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'26',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'99', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'27',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'100', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'27',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'101', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES POST OPERATORIAS', 	'pagina'=>'28',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'102', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'28',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'103', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'28',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'104', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'28',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'105', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'28',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'106', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'29',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'107', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'29',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'108', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'29',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'109', 	'nivel'=>'2', 	'nombre'=>'5. SINDROME ICTERICO OBSTRUCTIVO', 	'pagina'=>'30',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'110', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'30',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'111', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'30',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'112', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'30',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'113', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'30',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'114', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'31',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'115', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'31',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'116', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'31',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'117', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'31',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'118', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'31',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'119', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO PRE QUIRURGICO', 	'pagina'=>'31',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'120', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'32',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'121', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO ENDOSCOPICO', 	'pagina'=>'32',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'122', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'32',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'123', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'33',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'124', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'33',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'125', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'34',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'126', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'35',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'127', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'35',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'128', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'35',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'129', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'35',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'130', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'35',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'131', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'35',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'132', 	'nivel'=>'2', 	'nombre'=>'6. PANCREATITIS AGUDA (TRATAMIENTO QUIRURGICO)', 	'pagina'=>'36',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'133', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'36',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'134', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'36',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'135', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'36',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'136', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'36',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'137', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'37',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'138', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'37',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'139', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'37',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'140', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'37',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'141', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'38',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'142', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO PRE QUIRURGICO', 	'pagina'=>'38',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'143', 	'nivel'=>'3', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'38',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'144', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'39',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'145', 	'nivel'=>'3', 	'nombre'=>'PROCEDIMIENTO QUIRURGICO', 	'pagina'=>'39',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'146', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'40',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'147', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'41',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'148', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'41',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'149', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'41',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'150', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'41',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'151', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'41',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'152', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'42',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'153', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'42',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'154', 	'nivel'=>'2', 	'nombre'=>'7. HERNIA EPIGASTRICA', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'155', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'156', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'157', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'158', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'159', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'160', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'161', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'43',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'162', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'44',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'163', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'44',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'164', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO PRE QUIRURGICO', 	'pagina'=>'44',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'165', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'45',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'166', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'45',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'167', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'45',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'168', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'46',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'169', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'46',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'170', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'46',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'171', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'46',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'172', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'47',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'173', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'47',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'174', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'47',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'175', 	'nivel'=>'2', 	'nombre'=>'8. HERNIA UMBILICAL Y PARAUNBILICAL', 	'pagina'=>'48',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'176', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'48',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'177', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'48',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'178', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'48',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'179', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'48',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'180', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'48',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'181', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'48',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'182', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'49',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'183', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'49',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'184', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'49',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'185', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO HOSPITALARIO EN NIVEL II O III', 	'pagina'=>'49',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'186', 	'nivel'=>'3', 	'nombre'=>'MANEJO PRE OPERATORIO', 	'pagina'=>'49',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'187', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'49',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'188', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'50',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'189', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'50',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'190', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'50',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'191', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'51',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'192', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'52',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'193', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'52',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'194', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRAREFERENCIA', 	'pagina'=>'52',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'195', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'52',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'196', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'52',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'197', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'52',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'198', 	'nivel'=>'2', 	'nombre'=>'9. HERNIA INGUINAL', 	'pagina'=>'53',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'199', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'53',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'200', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'53',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'201', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'53',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'202', 	'nivel'=>'4', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'53',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'203', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'53',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'204', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'54',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'205', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'54',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'206', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'54',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'207', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'54',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'208', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'55',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'209', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'55',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'210', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'55',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'211', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'56',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'212', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'56',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'213', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'56',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'214', 	'nivel'=>'3', 	'nombre'=>'CUIDADOS POST OPERATORIOS', 	'pagina'=>'57',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'215', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'57',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'216', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'58',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'217', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'58',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'218', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'58',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'219', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'58',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'220', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'58',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'221', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'58',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'222', 	'nivel'=>'2', 	'nombre'=>'10. HERNIA CRURAL', 	'pagina'=>'59',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'223', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'59',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'224', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'59',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'225', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'59',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'226', 	'nivel'=>'4', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'59',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'227', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'59',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'228', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'59',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'229', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'60',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'230', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'60',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'231', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'60',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'232', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'60',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'233', 	'nivel'=>'3', 	'nombre'=>'MANEJO PRE OPERATORIO', 	'pagina'=>'61',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'234', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'61',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'235', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'61',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'236', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'62',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'237', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'62',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'238', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'63',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'239', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'63',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'240', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'63',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'241', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'63',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'242', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'64',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'243', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'64',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'244', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'64',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'245', 	'nivel'=>'2', 	'nombre'=>'11. VOLVULO DE SIGMOIDES', 	'pagina'=>'65',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'246', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'65',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'247', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'65',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'248', 	'nivel'=>'4', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'65',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'249', 	'nivel'=>'4', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'65',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'250', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'66',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'251', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'66',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'252', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'66',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'253', 	'nivel'=>'4', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'66',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'254', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'66',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'255', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO PRE QUIRURGICO', 	'pagina'=>'66',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'256', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'67',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'257', 	'nivel'=>'3', 	'nombre'=>'TRAMIENTO QUIRURGICO', 	'pagina'=>'68',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'258', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'68',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'259', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°2: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'68',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'260', 	'nivel'=>'3', 	'nombre'=>'CUIDADOS POST OPERATORIOS', 	'pagina'=>'69',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'261', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'69',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'262', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'69',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'263', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'69',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'264', 	'nivel'=>'3', 	'nombre'=>'CONTROL POST OPERATORIO DESPUES DEL ALTA', 	'pagina'=>'70',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'265', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'70',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'266', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'70',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'267', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'70',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'268', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'70',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'269', 	'nivel'=>'2', 	'nombre'=>'12. TRAUMA ABDOMINAL Y PELVICO', 	'pagina'=>'71',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'270', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'71',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'271', 	'nivel'=>'3', 	'nombre'=>'CLASIFICACION', 	'pagina'=>'71',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'272', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'71',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'273', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'71',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'274', 	'nivel'=>'2', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'72',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'275', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'72',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'276', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'72',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'277', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO PRE REFERENCIA EN NIVEL I O II', 	'pagina'=>'72',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'278', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'72',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'279', 	'nivel'=>'3', 	'nombre'=>'MANEJO PRE OPERATORIO', 	'pagina'=>'73',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'280', 	'nivel'=>'4', 	'nombre'=>'CUADRO N°1: LIQUIDOS IV DE MANTENIMIENTO EN NIÑOS/NIÑAS DE ACUERDO A SU PESO', 	'pagina'=>'73',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'281', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'74',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'282', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO POST QUIRURGICO', 	'pagina'=>'74',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'283', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'75',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'284', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'75',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'285', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE HOSPITALIZACION', 	'pagina'=>'75',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'286', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA MEDICA', 	'pagina'=>'75',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'287', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'75',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'288', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'75',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'289', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'75',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'290', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'76',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'291', 	'nivel'=>'1', 	'nombre'=>'UNIDAD 16. ENFERMEDADES DE LA PIEL Y DEL TEJIDO CELULAR SUBCUTANEO', 	'pagina'=>'77',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'292', 	'nivel'=>'1', 	'nombre'=>'CONTENIDO', 	'pagina'=>'78',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'293', 	'nivel'=>'1', 	'nombre'=>'I. ASPECTOS Y ANTIVIDADES DE APLICACIÓN FUNDAMENTAL', 	'pagina'=>'79',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'294', 	'nivel'=>'2', 	'nombre'=>'1. PREVENCION DE ESTILOS DE VIDA NO SALUDABLES', 	'pagina'=>'79',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'295', 	'nivel'=>'3', 	'nombre'=>'ANTECEDENTES', 	'pagina'=>'79',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'296', 	'nivel'=>'4', 	'nombre'=>'CAMPOS DE SALUD DE LALONDE', 	'pagina'=>'79',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'297', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS RELACIONADAS CON ESTILOS DE VIDA NO SALUDABLES', 	'pagina'=>'80',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'298', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS EN ADOLESCENTES', 	'pagina'=>'80',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'299', 	'nivel'=>'1', 	'nombre'=>'II. NORMAS NACIONALES DE ATENCION CLINICA', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'300', 	'nivel'=>'2', 	'nombre'=>'1. ACNE', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'301', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'302', 	'nivel'=>'3', 	'nombre'=>'FACTORES PREDISPONENTES', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'303', 	'nivel'=>'3', 	'nombre'=>'CLASIFICACION SEGÚN EL GRUPO LATINOAMERICANO DE ESTUDIO DEL ACNE (GLEA)', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'304', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'305', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'306', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'81',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'307', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'82',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'308', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES Y ESPECIFICAS', 	'pagina'=>'82',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'309', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'82',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'310', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'82',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'311', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'82',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'312', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'83',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'313', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'83',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'314', 	'nivel'=>'2', 	'nombre'=>'2. CANCER DE PIEL', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'315', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'316', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'317', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'318', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'319', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'320', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'321', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUR', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'322', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'323', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'324', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'325', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'326', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'327', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'84',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'328', 	'nivel'=>'2', 	'nombre'=>'3. DERMATITIS ATOPICA', 	'pagina'=>'85',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'329', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'85',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'330', 	'nivel'=>'3', 	'nombre'=>'FACTORES PREDISPONENTES O DESENCADENANTES', 	'pagina'=>'85',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'331', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'85',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'332', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'85',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'333', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'85',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'334', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'85',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'335', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'336', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES Y ESPECIFICAS', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'337', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'338', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'339', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'340', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'341', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'342', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'86',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'343', 	'nivel'=>'2', 	'nombre'=>'4. DERMATITIS DEL PAÑAL', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'344', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'345', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'346', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'347', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'348', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'349', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'350', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'351', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'352', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'353', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'354', 	'nivel'=>'3', 	'nombre'=>'RECOMENDACIONES', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'355', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'356', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'87',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'357', 	'nivel'=>'2', 	'nombre'=>'5. ECTIMA', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'358', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'359', 	'nivel'=>'3', 	'nombre'=>'ETIOLOGIA', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'360', 	'nivel'=>'3', 	'nombre'=>'FACTORES PREDISPONENTES', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'361', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'362', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'363', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'364', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'365', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'366', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'367', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'88',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'368', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'89',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'369', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MENOS A 49 KG.', 	'pagina'=>'89',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'370', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MAYOR A 40 KG. ADULTOS Y ANCIANOS', 	'pagina'=>'89',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'371', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'89',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'372', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'89',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'373', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'89',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'374', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'89',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'375', 	'nivel'=>'2', 	'nombre'=>'6. ERISIPELA-CELULITIS', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'376', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'377', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'378', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'379', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'380', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'381', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'382', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MENOR A 40 KB.', 	'pagina'=>'90',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'383', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MAYOR A 40 KG. ADULTOS Y ANCIANOS', 	'pagina'=>'91',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'384', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'91',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'385', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'91',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'386', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'91',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'387', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'91',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'388', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'91',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'389', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'91',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'390', 	'nivel'=>'2', 	'nombre'=>'7. FORUNCULO Y ANTRAX', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'391', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'392', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'393', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'394', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'395', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'396', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'397', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'398', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MENOR A 40 KB.', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'399', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MAYOR A 40 KG. ADULTOS Y ANCIANOS', 	'pagina'=>'92',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'400', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'93',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'401', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'93',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'402', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'93',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'403', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'93',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'404', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'93',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'405', 	'nivel'=>'2', 	'nombre'=>'8. FOTODERMATOSIS', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'406', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'407', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'408', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'409', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'410', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'411', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'412', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'413', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'414', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'94',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'415', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'95',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'416', 	'nivel'=>'2', 	'nombre'=>'9. HEMANGIOMA INFANTIL', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'417', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'418', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'419', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'420', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'421', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'422', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'423', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'424', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'425', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'96',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'426', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'97',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'427', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'97',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'428', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'97',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'429', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'97',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'430', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'97',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'431', 	'nivel'=>'2', 	'nombre'=>'10. IMPETIGO', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'432', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'433', 	'nivel'=>'3', 	'nombre'=>'CLASIFICACION', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'434', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'435', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'436', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'437', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'438', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'439', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'440', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MENOR A 40 KB.', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'441', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MAYOR A 40 KG. ADULTOS Y ANCIANOS', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'442', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'98',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'443', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'99',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'444', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'99',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'445', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'99',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'446', 	'nivel'=>'2', 	'nombre'=>'11. ROSACEA', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'447', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'448', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'449', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'450', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'451', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'452', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'453', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES Y ESPECIFICAS', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'454', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'455', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'456', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'457', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'100',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'458', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'101',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'459', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'101',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'460', 	'nivel'=>'2', 	'nombre'=>'12. UÑA ENCARNADA', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'461', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'462', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'463', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'464', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'465', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO DIFERENCIAL', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'466', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'467', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'468', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES Y ESPECIFICAS', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'469', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'470', 	'nivel'=>'3', 	'nombre'=>'MANEJO QUIRURGICO: NIVEL II Y III', 	'pagina'=>'102',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'471', 	'nivel'=>'3', 	'nombre'=>'MANEJO POST QUIRURGICO EN NIVEL II Y III', 	'pagina'=>'103',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'472', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'103',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'473', 	'nivel'=>'3', 	'nombre'=>'PIE SEPTICO MANEJO POR TRAUMATOLOGIA', 	'pagina'=>'103',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'474', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'103',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'475', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO DE PRE-REFERENCIA TRAUMATOLOGIA', 	'pagina'=>'103',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'476', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO EN NIVEL II Y III', 	'pagina'=>'104',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'477', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO DEL PIE SEPTICO O DEL PIE DIABETICO INFECTADO', 	'pagina'=>'104',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'478', 	'nivel'=>'3', 	'nombre'=>'COMPLICACIONES POST OPERATORIAS', 	'pagina'=>'104',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'479', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'104',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'480', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'104',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'481', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'104',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'482', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'104',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'483', 	'nivel'=>'2', 	'nombre'=>'13. URTICARIA Y ANGIOEDEMA', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'484', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'485', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'486', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'487', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'488', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO MEDICO', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'489', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'490', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MENOR A 40 KB.', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'491', 	'nivel'=>'3', 	'nombre'=>'NIÑOS CON PESO MAYOR A 40 KG. ADULTOS Y ANCIANOS', 	'pagina'=>'105',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'492', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'106',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'493', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'106',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'494', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'106',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'495', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'106',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'496', 	'nivel'=>'2', 	'nombre'=>'14. ULCERAS POR PRESION', 	'pagina'=>'107',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'497', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'107',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'498', 	'nivel'=>'3', 	'nombre'=>'ETIOLOGIA', 	'pagina'=>'107',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'499', 	'nivel'=>'3', 	'nombre'=>'FACTORES DE RIESGO', 	'pagina'=>'107',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'500', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'107',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'501', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'107',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'502', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'108',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'503', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'108',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'504', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'109',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'505', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'109',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'506', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'109',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'507', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'109',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'508', 	'nivel'=>'1', 	'nombre'=>'UNIDAD 17. EMFERMEDADES DEL TEJIDO OSTEOMUSCULAR Y CONJUNTIVO', 	'pagina'=>'111',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'509', 	'nivel'=>'1', 	'nombre'=>'CONTENIDO', 	'pagina'=>'112',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'510', 	'nivel'=>'1', 	'nombre'=>'I. ASPECTOS Y ANTIVIDADES DE APLICACIÓN FUNDAMENTAL', 	'pagina'=>'113',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'511', 	'nivel'=>'2', 	'nombre'=>'ANTECEDENTES', 	'pagina'=>'113',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'512', 	'nivel'=>'2', 	'nombre'=>'CAMPOS DE SALUD DE LALONDE', 	'pagina'=>'113',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'513', 	'nivel'=>'2', 	'nombre'=>'MEDIDAS PREVENTIVAS RELACIONADAS CON ESTILOS DE VIDA NO SALUDABLES', 	'pagina'=>'114',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'514', 	'nivel'=>'2', 	'nombre'=>'MEDIDAS PREVENTIVAS EN ADOLESCENTES', 	'pagina'=>'114',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'515', 	'nivel'=>'1', 	'nombre'=>'II. NORMAS NACIONALES DE ATENCION CLINICA', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'516', 	'nivel'=>'2', 	'nombre'=>'1. ARTRITIS REUMATOIDE', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'517', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'518', 	'nivel'=>'3', 	'nombre'=>'ETIOLOGIA', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'519', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'520', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'521', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'522', 	'nivel'=>'3', 	'nombre'=>'COMORBILIDADES', 	'pagina'=>'115',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'523', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DIAGNOSTICOS DE LA ARTRITIS REUMATOIDE', 	'pagina'=>'116',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'524', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO RE', 	'pagina'=>'116',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'525', 	'nivel'=>'3', 	'nombre'=>'CATEGORIA', 	'pagina'=>'116',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'526', 	'nivel'=>'3', 	'nombre'=>'EJEMPLOS COMUNES', 	'pagina'=>'116',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'527', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'116',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'528', 	'nivel'=>'3', 	'nombre'=>'MEDIDASD GENERALES INICIALES', 	'pagina'=>'116',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'529', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO NO FARMACOLOGICO', 	'pagina'=>'116',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'530', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'531', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO FARMACOLOGICO', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'532', 	'nivel'=>'3', 	'nombre'=>'ANTIINFLAMATORIOS NO ESTEROIDEOS', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'533', 	'nivel'=>'3', 	'nombre'=>'FARMACOS ANTIREUMATICOS MODIFICADORES DEL CURSO DE LA ENFERMEDAD (FARME)', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'534', 	'nivel'=>'3', 	'nombre'=>'GLUCOCORTICOIDES', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'535', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'536', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'537', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'538', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'539', 	'nivel'=>'3', 	'nombre'=>'OBSERVACIONES', 	'pagina'=>'117',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'540', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'118',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'541', 	'nivel'=>'2', 	'nombre'=>'2. ARTROSIS OSTEOARTRITIS', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'542', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'543', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'544', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'545', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'546', 	'nivel'=>'3', 	'nombre'=>'TRATEMIENTO MEDICO', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'547', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'548', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO NO FARMACOLOGICO', 	'pagina'=>'119',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'549', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'120',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'550', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO FARMACOLOGICO', 	'pagina'=>'120',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'551', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'120',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'552', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'120',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'553', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'120',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'554', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'120',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'555', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'120',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'556', 	'nivel'=>'2', 	'nombre'=>'3. DISPLASIA DEL DESARROLLO DE LA CADERA (DDC)', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'557', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'558', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'559', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'560', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'561', 	'nivel'=>'3', 	'nombre'=>'CLASIFICACION', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'562', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'563', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'121',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'564', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'122',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'565', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'122',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'566', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'122',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'567', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'122',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'568', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'122',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'569', 	'nivel'=>'2', 	'nombre'=>'4. FASCITIS NECROSANTE', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'570', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'571', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'572', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'573', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'574', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'575', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'576', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'123',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'577', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO QUIRURGICO', 	'pagina'=>'124',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'578', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'124',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'579', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'124',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'580', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'124',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'581', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'124',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'582', 	'nivel'=>'2', 	'nombre'=>'5. FRATURA DE CLAVICULA', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'583', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'584', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'585', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'586', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'587', 	'nivel'=>'3', 	'nombre'=>'CLASIFICACION', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'588', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'589', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'590', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'591', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'592', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'593', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'594', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'125',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'595', 	'nivel'=>'2', 	'nombre'=>'6. FRACTURA PROXIMAL DEL HUMERO', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'596', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'597', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'598', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'599', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'600', 	'nivel'=>'3', 	'nombre'=>'CLASIFICACION', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'601', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'602', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'603', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'604', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'605', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'606', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'607', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'126',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'608', 	'nivel'=>'2', 	'nombre'=>'7. FRACTURA DE DIAFISIS HUMERAL', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'609', 	'nivel'=>'3', 	'nombre'=>'DEFINICION', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'610', 	'nivel'=>'3', 	'nombre'=>'DIAGNOSTICO', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'611', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS CLINICOS', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'612', 	'nivel'=>'3', 	'nombre'=>'EXAMENES COMPLEMENTARIOS', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'613', 	'nivel'=>'3', 	'nombre'=>'CLASIFICACION', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'614', 	'nivel'=>'3', 	'nombre'=>'TRATAMIENTO', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'615', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS GENERALES', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'616', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS ESPECIFICAS', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'617', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE REFERENCIA', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'618', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE ALTA', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'619', 	'nivel'=>'3', 	'nombre'=>'CRITERIOS DE CONTRARREFERENCIA', 	'pagina'=>'127',]);
        Marcador::create([	'libro_id'=>'1', 	'numero'=>'620', 	'nivel'=>'3', 	'nombre'=>'MEDIDAS PREVENTIVAS HIGIENICO DIETETICAS Y ORIENTACION EN SERVICIO FAMILIA O CUMUNIDAD', 	'pagina'=>'127',]);

    }
}
