<?php

use App\Modelos\Marcador;
use Illuminate\Database\Seeder;

class Marcador5Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'1', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 1 - DISPOSICIONES GENERALES', 	'pagina'=>'1', 	'vistaprevia'=>'1.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'1', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 1 - DE LA DEFINICIÓN, ÁMBITO DE APLICACIÓN, OBJETO Y PRINCIPIO', 	'pagina'=>'1', 	'vistaprevia'=>'1.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'1', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 1.- DEFINICIÓN', 	'pagina'=>'1', 	'vistaprevia'=>'1.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'1', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 2.- ÁMBITO DE APLICACIÓN', 	'pagina'=>'2', 	'vistaprevia'=>'2.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'1', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 3.- OBJETO', 	'pagina'=>'2', 	'vistaprevia'=>'2.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'1', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 4.- PRINCIPIOS', 	'pagina'=>'2', 	'vistaprevia'=>'2.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 2 - TRABAJADORES EN SALUD', 	'pagina'=>'3', 	'vistaprevia'=>'3.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 1 - DEL TIPO DE EMPLEO', 	'pagina'=>'3', 	'vistaprevia'=>'3.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 5.- CATEGORÍAS DE EMPLEO', 	'pagina'=>'3', 	'vistaprevia'=>'3.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 2 - DERECHOS, OBLIGACIONES, PROHIBICIONES E INCOMPATIBILIDADES', 	'pagina'=>'3', 	'vistaprevia'=>'3.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 6.- DERECHOS', 	'pagina'=>'3', 	'vistaprevia'=>'3.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 7.- OBLIGACIONES O DEBERES', 	'pagina'=>'4', 	'vistaprevia'=>'4.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'2', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 8.- PROHIBICIONES E INCOMPATIBILIDADES', 	'pagina'=>'5', 	'vistaprevia'=>'5.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 3 - CARRERA ADMINISTRATIVA', 	'pagina'=>'5', 	'vistaprevia'=>'5.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 1 - DEL SISTEMA DE GESTIÓN DE RECURSOS HUMANOS', 	'pagina'=>'5', 	'vistaprevia'=>'5.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 9.- SISTEMA DE GESTIÓ DE RECURSOS HUMANOS', 	'pagina'=>'5', 	'vistaprevia'=>'5.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 2 - SUBSISTEMA DE INFORMACIÓN Y PLANIFICACIÓN ESTRATÉGICA', 	'pagina'=>'5', 	'vistaprevia'=>'5.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 10.- DEFINICIÓN', 	'pagina'=>'6', 	'vistaprevia'=>'6.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 11.- POLÍTICA', 	'pagina'=>'6', 	'vistaprevia'=>'6.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 12.- GENERACIÓN DE LA INFORMACIÓN', 	'pagina'=>'6', 	'vistaprevia'=>'6.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 13.- ORGANIZACIÓN DE LA INFORMACIÓN', 	'pagina'=>'6', 	'vistaprevia'=>'6.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 14.- DIFUSIÓN DE LA INFORMACIÓN', 	'pagina'=>'6', 	'vistaprevia'=>'6.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 15.- RECOPILACIÓN DE ANÁLISIS DE INFORMACIÓN', 	'pagina'=>'7', 	'vistaprevia'=>'7.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 16.- ESTABLECIMIENTO DE LAS NECESIDADES DEL PERSONAL', 	'pagina'=>'7', 	'vistaprevia'=>'7.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 17.- ELABORACIÓN DE LOS PLANES ESTRATÉGICOS DE RECURSOS HUMANOS', 	'pagina'=>'7', 	'vistaprevia'=>'7.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 3 - SUBSISTEMA DE ADMINISTRACIÓN DE CARGOS', 	'pagina'=>'7', 	'vistaprevia'=>'7.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 18.- DEFINICIÓN', 	'pagina'=>'7', 	'vistaprevia'=>'7.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 19.- POLÍTICA', 	'pagina'=>'7', 	'vistaprevia'=>'7.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 20.- DISEÑO DE CARGOS', 	'pagina'=>'7', 	'vistaprevia'=>'7.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 21.- CLASIFICACIÓN DE CARGOS', 	'pagina'=>'8', 	'vistaprevia'=>'8.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 4 - SUBSISTEMA DE RETRIBUCIONES', 	'pagina'=>'8', 	'vistaprevia'=>'8.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 22.- DEFINICIÓN', 	'pagina'=>'8', 	'vistaprevia'=>'8.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 23.- REMUNERACIÓN', 	'pagina'=>'8', 	'vistaprevia'=>'8.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 24.- POLÍTICA', 	'pagina'=>'8', 	'vistaprevia'=>'8.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 25.- RETRIBUCIÓN ECONÓMICA', 	'pagina'=>'8', 	'vistaprevia'=>'8.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 26.- RESPONSABILIDAD EN EL SUBSISTEMA DE RETRIBUCIÓN', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 27.- SALARIOS Y OTROS BENEFICIOS ECONÓMICOS', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 28.- EQUIVALENCIA EN LAS REMUNERACIONES', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 29.- CASOS EN LOS QUE SE PROHÍBE PAGAR REMUNERACIÓN', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 30.- ELABORACIÓN DE PLANILLAS', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 31.- DETERMINACIÓN DE PRESTACIONES', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 32.- PROCESO DE RETRIBUCIÓN NO ECONÓMICA', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 33.- OPORTUNIDAD', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 34.- RECONOCIMIENTO A LOS RESULTADOS DEL DESEMPEÑO', 	'pagina'=>'9', 	'vistaprevia'=>'9.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 5 - SUBSISTEMA DE INTEGRACIÓN DE RECURSOS HUMANOS', 	'pagina'=>'10', 	'vistaprevia'=>'10.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 35.- DEFINICIÓN', 	'pagina'=>'10', 	'vistaprevia'=>'10.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 36.- POLÍTICA', 	'pagina'=>'10', 	'vistaprevia'=>'10.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 37.- RECLUTAMIENTO', 	'pagina'=>'10', 	'vistaprevia'=>'10.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 38.- SELECCIÓN', 	'pagina'=>'10', 	'vistaprevia'=>'10.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 39.- NOMBRAMIENTO', 	'pagina'=>'11', 	'vistaprevia'=>'11.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 40.- INDUCCIÓN', 	'pagina'=>'11', 	'vistaprevia'=>'11.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 41.- EVALUACIÓN DE LA CONFIRMACIÓN', 	'pagina'=>'11', 	'vistaprevia'=>'11.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 6 - SUBSISTEMA DE ADMINISTRACIÓN DEL DESEMPEÑO', 	'pagina'=>'11', 	'vistaprevia'=>'11.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 42.- DEFINICIÓN', 	'pagina'=>'11', 	'vistaprevia'=>'11.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 43.- POLÍTICA', 	'pagina'=>'11', 	'vistaprevia'=>'11.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 44.- PROGRAMACIÓN DE LA EVALUACIÓN', 	'pagina'=>'11', 	'vistaprevia'=>'11.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 45.- EJECUCIÓN DE LA EVALUACIÓN', 	'pagina'=>'12', 	'vistaprevia'=>'12.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 46.- DEFINICIÓN', 	'pagina'=>'12', 	'vistaprevia'=>'12.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 47.- POLÍTICA', 	'pagina'=>'12', 	'vistaprevia'=>'12.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 48.- DETECCIÓN DE NECESIDADES', 	'pagina'=>'12', 	'vistaprevia'=>'12.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 49.- PROGRAMACIÓN DE LA CAPACITACIÓN', 	'pagina'=>'12', 	'vistaprevia'=>'12.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 50.- EJECUCIÓN DEL PROCESO DE CAPACITACIÓN', 	'pagina'=>'13', 	'vistaprevia'=>'13.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 51.- EVALUACIÓN DEL PROCESO DE LA CAPACITACIÓN', 	'pagina'=>'13', 	'vistaprevia'=>'13.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 52.- EVALUACIÓN DE LOS RESULTADOS DE LA CAPACITACIÓN', 	'pagina'=>'13', 	'vistaprevia'=>'13.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 53.- BECAS', 	'pagina'=>'14', 	'vistaprevia'=>'14.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 54.- PASANTÍAS', 	'pagina'=>'14', 	'vistaprevia'=>'14.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 7 - SUBSISTEMA DE MOVILIDAD DE RECURSOS HUMANOS', 	'pagina'=>'15', 	'vistaprevia'=>'15.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 55.- DEFINICIÓN', 	'pagina'=>'15', 	'vistaprevia'=>'15.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 56.- POLÍTICA', 	'pagina'=>'15', 	'vistaprevia'=>'15.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 57.- PROMOCIÓN', 	'pagina'=>'15', 	'vistaprevia'=>'15.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 58.- ROTACIÓN DE PERSONAL', 	'pagina'=>'16', 	'vistaprevia'=>'16.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 59.- PERMUTA', 	'pagina'=>'16', 	'vistaprevia'=>'16.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 60.-TRANSFERENCIA', 	'pagina'=>'16', 	'vistaprevia'=>'16.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 61.- SANCIONES Y RETIRO', 	'pagina'=>'16', 	'vistaprevia'=>'16.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 9 - SUBSISTEMA DE AUDITORÍA DE RECURSOS HUMANOS', 	'pagina'=>'16', 	'vistaprevia'=>'16.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 62.- DEFINICIÓN', 	'pagina'=>'17', 	'vistaprevia'=>'17.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 63.- POLÍTICA', 	'pagina'=>'17', 	'vistaprevia'=>'17.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 64.- RECOPILACIÓN DE INFORMACIÓN', 	'pagina'=>'17', 	'vistaprevia'=>'17.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 65.- COMITÉ DE AUDITORÍA', 	'pagina'=>'17', 	'vistaprevia'=>'17.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 66.- IDENTIFICACIÓN DE DEFICIENCIAS', 	'pagina'=>'17', 	'vistaprevia'=>'17.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO  67.- EVALUACIÓN DE LA INFORMACIÓN', 	'pagina'=>'17', 	'vistaprevia'=>'17.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 68.- ESTÁNDARES', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 69.- INFORMACIÓN', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 70.- ACCIONES CORRECTIVAS', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'3', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 71.- PROYECTOS DE MEJORAMIENTO', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'4', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 4 - REGIMEN LABORAL', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'4', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 1 - DEL HORARIO DE TRABAJO, PERMISOS Y LICENCIAS', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'4', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 72.- PERMISOS', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'4', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 73.- LICENCIAS', 	'pagina'=>'18', 	'vistaprevia'=>'18.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'4', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO 2 - VACACIONES', 	'pagina'=>'19', 	'vistaprevia'=>'19.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'4', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 74.- VACACIONES', 	'pagina'=>'19', 	'vistaprevia'=>'19.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'5', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 5 ', 	'pagina'=>'19', 	'vistaprevia'=>'19.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'5', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO ÚNICO -DECLARACIÓN DE BIENES Y RENTAS', 	'pagina'=>'19', 	'vistaprevia'=>'19.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'5', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 75.- DECLARACIÓN DE BIENES Y RENTAS', 	'pagina'=>'19', 	'vistaprevia'=>'19.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'5', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 76.- PRINCIPIOS', 	'pagina'=>'19', 	'vistaprevia'=>'19.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'6', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 6 - PROCEDIMIENTO ADMINISTRATIVOS Y SUPERVISIÓN DEL RÉGIMEN DE CARRERA', 	'pagina'=>'19', 	'vistaprevia'=>'19.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'6', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 77.- PROCEDIMIENTO ADMINISTRATIVO PARA LA TRAMITACIÓN DE RECLAMOS', 	'pagina'=>'20', 	'vistaprevia'=>'20.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'6', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 78.- RESOLUCIONES DENEGATORIAS DE LOS RECURSOS DE REVOCATORIA', 	'pagina'=>'20', 	'vistaprevia'=>'20.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'7', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 7', 	'pagina'=>'20', 	'vistaprevia'=>'20.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'7', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO ÚNICO - DISPOSICIONES COMPLEMENTARIAS Y TRANSITORIAS', 	'pagina'=>'20', 	'vistaprevia'=>'20.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'7', 	'nivel'=>'1', 	'nombre'=>'ARTÍCULO 79.- REGULARIZACIONES DE LOS TRABAJADORES DE CARRERA', 	'pagina'=>'20', 	'vistaprevia'=>'20.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'8', 	'nivel'=>'1', 	'nombre'=>'TÍTULO 8', 	'pagina'=>'20', 	'vistaprevia'=>'20.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
        Marcador::create([	'libro_id'=>'5', 	'tipomarcador_id'=>'1', 	'numero'=>'8', 	'nivel'=>'1', 	'nombre'=>'CAPÍTULO ÚNICO - CÓDIGO DE ÉTICA', 	'pagina'=>'20', 	'vistaprevia'=>'20.PNG', 	'created_at'=>'2020-17-10', 	'updated_at'=>'2020-17-10', 	'estado'=>'1',]);
    }
}
