<?php

use App\Modelos\Respuesta;
use Illuminate\Database\Seeder;

class RespuestaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
/*
        for ($i=1; $i <= 50 ; $i++) {
            # code...
            factory(Respuesta::class, 1)->create(['pregunta_id' => $i, 'escorrecta' => 1]);
            factory(Respuesta::class, 3)->create(['pregunta_id' => $i, 'escorrecta' => 0]);
        }
*/
        Respuesta::create([	'pregunta_id'=>'1', 	'respuesta'=>'Disminuir la Morbimortalidad por Tuberculosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'1', 	'respuesta'=>'Reducir la Transmisión del Mycobacterium tuberculosis en la comunidad', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'1', 	'respuesta'=>'Detectar las complicaciones por tuberculosis', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'1', 	'respuesta'=>'Evitar la drogorresistencia', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'2', 	'respuesta'=>'Detectar el 90% de los sintomáticos respiratorios', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'2', 	'respuesta'=>'Capacitar al todo el personal de salud', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'2', 	'respuesta'=>'Entregar alimentos a los pacientes de tuberculosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'2', 	'respuesta'=>'Reunirse cada mes con los pacientes de tuberculosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'3', 	'respuesta'=>'Tener salas de aislamiento para pacientes en todos los hospitales', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'3', 	'respuesta'=>'Curar y terminar el tratamiento al menos al 85% de los casos nuevos de TB', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'3', 	'respuesta'=>'Tener un responsable de programa en cada establecimiento de salud', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'3', 	'respuesta'=>'Realizar ferias de salud cada año', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'4', 	'respuesta'=>'Tuberculosis multidrogorresistente', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'4', 	'respuesta'=>'Tuberculosis infantil', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'4', 	'respuesta'=>'Tuberculosis extrapulmonar', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'4', 	'respuesta'=>'Tuberculosis presuntiva', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'5', 	'respuesta'=>'Confirmada por radiografía', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'5', 	'respuesta'=>'Confirmada por Genexpert', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'5', 	'respuesta'=>'Confirmada por biopsia', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'5', 	'respuesta'=>'Confirmada por clínica', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'6', 	'respuesta'=>'Confirmada por baciloscopía seriada', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'6', 	'respuesta'=>'Confirmada por tomografía', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'6', 	'respuesta'=>'Confirmada por anatomía patológica', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'6', 	'respuesta'=>'Confirmada por clínica', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'7', 	'respuesta'=>'Tuberculosis meningea y pleural', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'7', 	'respuesta'=>'Tuberculosis sensible y resistente', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'7', 	'respuesta'=>'Tuberculosis pulmonar y extrapulmonar', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'7', 	'respuesta'=>'Tuberculosis pediatrica y tuberculosis de adultos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'8', 	'respuesta'=>'Paciente con recaida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'8', 	'respuesta'=>'Paciente nuevo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'8', 	'respuesta'=>'Paciente con fracaso', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'8', 	'respuesta'=>'Paciente previamente tratado', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'9', 	'respuesta'=>'Paciente que tuvo un fracaso anterior', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'9', 	'respuesta'=>'Paciente que nunca recibio tratamiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'9', 	'respuesta'=>'Paciente abandono recuperado', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'9', 	'respuesta'=>'Paciente tratado previamente por tuberculosis', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'10', 	'respuesta'=>'Paciente curado', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'10', 	'respuesta'=>'Tratamiento completo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'10', 	'respuesta'=>'Fracaso al tratamiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'10', 	'respuesta'=>'Pérdida en el seguimiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'11', 	'respuesta'=>'Paciente curado', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'11', 	'respuesta'=>'Tratamiento completo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'11', 	'respuesta'=>'Fracaso al tratamiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'11', 	'respuesta'=>'Pérdida en el seguimiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'12', 	'respuesta'=>'Paciente curado', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'12', 	'respuesta'=>'Tratamiento completo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'12', 	'respuesta'=>'Fracaso al tratamiento', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'12', 	'respuesta'=>'Pérdida en el seguimiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'13', 	'respuesta'=>'Paciente curado', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'13', 	'respuesta'=>'Tratamiento completo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'13', 	'respuesta'=>'Fracaso al tratamiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'13', 	'respuesta'=>'Pérdida en el seguimiento', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'14', 	'respuesta'=>'Mycobacteirum leprae', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'14', 	'respuesta'=>'Mycobacterium tuberculosis', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'14', 	'respuesta'=>'Mycoplasma', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'14', 	'respuesta'=>'Bacilo de Hansen', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'15', 	'respuesta'=>'Infección tuberculosa', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'15', 	'respuesta'=>'Enfermedad tuberculosa', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'15', 	'respuesta'=>'Resistencia tuberculosa', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'15', 	'respuesta'=>'Inmunidad natural', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'16', 	'respuesta'=>'Contacto con cubiertos y platos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'16', 	'respuesta'=>'Saludar con la mano', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'16', 	'respuesta'=>'Compartir ropa', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'16', 	'respuesta'=>'Vía aerea por medio de la tos, estornudos, hablar', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'17', 	'respuesta'=>'Hiporexia, astenia, pérdida de peso', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'17', 	'respuesta'=>'Tos por más de 15 días', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'17', 	'respuesta'=>'Hemoptisis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'17', 	'respuesta'=>'Disnea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'18', 	'respuesta'=>'Sudoración nocturna', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'18', 	'respuesta'=>'Febrícula', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'18', 	'respuesta'=>'Tos con expectoración por más de 15 días', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'18', 	'respuesta'=>'Pérdida de peso', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'19', 	'respuesta'=>'Persona que pierde peso sin causa aparente', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'19', 	'respuesta'=>'Persona con tos con expectoración por más de 15 días', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'19', 	'respuesta'=>'Persona que pierde el apetito', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'19', 	'respuesta'=>'Persona que tiene mucha sudoración nocturna', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'20', 	'respuesta'=>'Captación del sospechoso en la visita domiciliaria', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'20', 	'respuesta'=>'Captación del sospechoso en las ferias de salud', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'20', 	'respuesta'=>'Captación en las carceles y centros de acogida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'20', 	'respuesta'=>'Captación del sospechoso en las consultas médicas en establecimientos de salud, brigadas móviles, salas de emergencia', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'21', 	'respuesta'=>'Grupos poblacionales de riesgo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'21', 	'respuesta'=>'En los hospitales', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'21', 	'respuesta'=>'En las salas de emergencia de los hospitales', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'21', 	'respuesta'=>'En las consultas médicas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'22', 	'respuesta'=>'La búsqueda activa', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'22', 	'respuesta'=>'Las visitas domiciliarias', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'22', 	'respuesta'=>'La detección pasiva', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'22', 	'respuesta'=>'La visita a las cárceles', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'23', 	'respuesta'=>'La radiografía', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'23', 	'respuesta'=>'Los síntomas y signos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'23', 	'respuesta'=>'La biopsia', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'23', 	'respuesta'=>'El cultivo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'24', 	'respuesta'=>'Bacilos de recuento en el extendido', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'24', 	'respuesta'=>'10 a 99 BAAR en 100 campos microscópicos observados', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'24', 	'respuesta'=>'1 a 10 BAAR por campo en 50 campos microsocópicos observados', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'24', 	'respuesta'=>'Más de 10 BAAR por campo en 20 campos microscópicos ', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'25', 	'respuesta'=>'Al momento de que el personal de salud identifica al sospechoso', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'25', 	'respuesta'=>'Al siguiente día en ayunas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'25', 	'respuesta'=>'A los dos días en ayunas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'25', 	'respuesta'=>'No importa el tiempo siempre y cuando la muestra sea en ayunas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'26', 	'respuesta'=>'El Genexpert', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'26', 	'respuesta'=>'La baciloscopía seriada', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'26', 	'respuesta'=>'El cultivo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'26', 	'respuesta'=>'La radiografía', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'27', 	'respuesta'=>'Paciente que todos los meses sus controles dan negativos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'27', 	'respuesta'=>'Personal de salud sospechoso', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'27', 	'respuesta'=>'Mujeres embarazadas sospechosas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'27', 	'respuesta'=>'Sintomático respiratorio con BK seriada negativa, tratado con antibióticos no quinolonas, y sin mejoría clínica', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'28', 	'respuesta'=>'Personal de salud sospechoso', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'28', 	'respuesta'=>'Paciente con resultado 1 a 9 BAAR en una sola lámina de las dos observadas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'28', 	'respuesta'=>'Sintomático respiratorio con BK negativa, tratado con antibióticos no quinolonas, y sin mejoría clínica', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'28', 	'respuesta'=>'Para dar condición de egreso al 4to o 5to mes ', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'29', 	'respuesta'=>'Cultivo de Ogawa', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'29', 	'respuesta'=>'Tinción de Ziehl-Nielsen', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'29', 	'respuesta'=>'Genexpert', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'29', 	'respuesta'=>'Bacilosocpía seriada', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'30', 	'respuesta'=>'Tuberculosis presuntiva en personal de salud', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'30', 	'respuesta'=>'Antes de dar de alta al paciente', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'30', 	'respuesta'=>'Si sale positiva la baciloscopía al segundo mes de tratamiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'30', 	'respuesta'=>'Para detectar tuberculosis renal', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'31', 	'respuesta'=>'Casos de TB BK (-) con signos y síntomas sugestivos de TB.', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'31', 	'respuesta'=>'Antes de dar de alta al paciente', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'31', 	'respuesta'=>'Tuberculosis presuntiva en personas privadas de libertad (PPL).', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'31', 	'respuesta'=>'Tuberculosis presuntiva en el Personal de salud.', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'32', 	'respuesta'=>'Líquido cefalorraquídeo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'32', 	'respuesta'=>'Heces', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'32', 	'respuesta'=>'Orina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'32', 	'respuesta'=>'Sangre', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'33', 	'respuesta'=>'Estrictamente supervisado en todos los pacientes el tiempo que dure el tratamiento', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'33', 	'respuesta'=>'Supervisado solo en pacientes que son renuentes al tratamiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'33', 	'respuesta'=>'Tomar una tableta cada 4 horas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'33', 	'respuesta'=>'Estrictamente supervisado solo el primer mes', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'34', 	'respuesta'=>'Amikacina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'34', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'34', 	'respuesta'=>'Cicloserina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'34', 	'respuesta'=>'Levofloxacina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'35', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'35', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'35', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'35', 	'respuesta'=>'Amikacina', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'36', 	'respuesta'=>'9 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'36', 	'respuesta'=>'Un año', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'36', 	'respuesta'=>'2 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'36', 	'respuesta'=>'6 meses', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'37', 	'respuesta'=>'25 mg/kilo peso', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'37', 	'respuesta'=>'5 - 10 mg/kilo eso dependiendo si el peso es menor de 25 kg', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'37', 	'respuesta'=>'1mg/kilo peso', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'37', 	'respuesta'=>'20 mg/kilo peso', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'38', 	'respuesta'=>'500 mg', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'38', 	'respuesta'=>'1 gr', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'38', 	'respuesta'=>'400 mg', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'38', 	'respuesta'=>'200 mg', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'39', 	'respuesta'=>'52 dosis', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'39', 	'respuesta'=>'104 dosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'39', 	'respuesta'=>'60 dosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'39', 	'respuesta'=>'26 dosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'40', 	'respuesta'=>'500 mg', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'40', 	'respuesta'=>'250 mg', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'40', 	'respuesta'=>'1 gr', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'40', 	'respuesta'=>'400 mg', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'41', 	'respuesta'=>'Creatinina y perfil lipídico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'41', 	'respuesta'=>'Prueba rápida de VIH y Glicemia', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'41', 	'respuesta'=>'Hemograma y Examen de orina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'41', 	'respuesta'=>'Grupo sanguíneo y coproparasitológico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'42', 	'respuesta'=>'Pasar a fase de continuación', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'42', 	'respuesta'=>'Suspender el tratamiento', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'42', 	'respuesta'=>'Prolongar fase intensiva un mes mas', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'42', 	'respuesta'=>'Se aumenta la dosis de medicamentos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'43', 	'respuesta'=>'Ser suspendido', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'43', 	'respuesta'=>'No se inicia tratamiento a embarazadas por peligro para el feto', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'43', 	'respuesta'=>'No se utiliza rifamipicina ni isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'43', 	'respuesta'=>'Se continua con el tratamiento pues no se han demostrado efectos graves sobre el feto', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'44', 	'respuesta'=>'Se suspende el tratamiento antituberculoso', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'44', 	'respuesta'=>'Puede seguir dando de lactar con medidas de protección personal sin suspender el tratamiento', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'44', 	'respuesta'=>'Se suspende la lactancia materna', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'44', 	'respuesta'=>'Se suspende la rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'45', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'45', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'45', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'45', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'46', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'46', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'46', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'46', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'47', 	'respuesta'=>'6 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'47', 	'respuesta'=>'8 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'47', 	'respuesta'=>'12 meses', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'47', 	'respuesta'=>'9 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'48', 	'respuesta'=>'Todas las formas de tuberculosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'48', 	'respuesta'=>'La Tuberculosis meningea y milliar', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'48', 	'respuesta'=>'La tuberculosis extrapulmonar', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'48', 	'respuesta'=>'La tuberculosis ganglionar', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'49', 	'respuesta'=>'Vacuna BCG', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'49', 	'respuesta'=>'Control de contactos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'49', 	'respuesta'=>'Quimioprofilaxis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'49', 	'respuesta'=>'Aislar a los pacientes en sus casas y que no salgan', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'50', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'50', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'50', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'50', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'51', 	'respuesta'=>'Menores de 5 años y pacientes con VIH', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'51', 	'respuesta'=>'Mayores de 60 años', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'51', 	'respuesta'=>'Mujeres embarazadas ', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'51', 	'respuesta'=>'Personal de salud    ', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'52', 	'respuesta'=>'1 año', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'52', 	'respuesta'=>'6 meses', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'52', 	'respuesta'=>'3meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'52', 	'respuesta'=>'1mes', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'53', 	'respuesta'=>'Menores de 5 años   ', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'53', 	'respuesta'=>'Pacientes con VIH', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'53', 	'respuesta'=>'Pacientes inmunosuprimidos con transplantes', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'53', 	'respuesta'=>'Contactos de pacientes Multidrogorresistentes', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'54', 	'respuesta'=>'Resistencia a solo un medicamento anti tuberculoso de primera línea', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'54', 	'respuesta'=>'Resistencia a más de un medicamento antituberculoso de primera línea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'54', 	'respuesta'=>'Resistencia conjunta a la Isoniacida y Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'54', 	'respuesta'=>'Paciente MDR y además resistente a fluoroquinolonas y a una de las dorgas inyectables de segunda línea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'55', 	'respuesta'=>'Resistencia a solo un medicamento anti tuberculoso de primera línea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'55', 	'respuesta'=>'Resistencia a más de un medicamento antituberculoso de primera línea (que no sea isoniacida y rifampicina a la vez)', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'55', 	'respuesta'=>'Resistencia conjunta a la Isoniacida y Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'55', 	'respuesta'=>'Paciente MDR y además resistente a fluoroquinolonas y a una de las dorgas inyectables de segunda línea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'56', 	'respuesta'=>'Resistencia a solo un medicamento anti tuberculoso de primera línea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'56', 	'respuesta'=>'Resistencia a más de un medicamento antituberculoso de primera línea (que no sea isoniacida y rifampicina a la vez)', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'56', 	'respuesta'=>'Resistencia conjunta a la Isoniacida y Rifampicina', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'56', 	'respuesta'=>'Paciente MDR y además resistente a fluoroquinolonas y a una de las dorgas inyectables de segunda línea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'57', 	'respuesta'=>'Resistencia a solo un medicamento anti tuberculoso de primera línea', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'57', 	'respuesta'=>'Resistencia a más de un medicamento antituberculoso de primera línea (que no sea isoniacida y rifampicina a la vez)', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'57', 	'respuesta'=>'Resistencia conjunta a la Isoniacida y Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'57', 	'respuesta'=>'Paciente MDR y además resistente a fluoroquinolonas y a una de las drogas inyectables de segunda línea', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'58', 	'respuesta'=>'Esquema fuera de norma', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'58', 	'respuesta'=>'Subdosificación', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'58', 	'respuesta'=>'Tratamiento estrictamente supervisado', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'58', 	'respuesta'=>'Co morbilidades', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'59', 	'respuesta'=>'Levofloxacina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'59', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'59', 	'respuesta'=>'Amikacina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'59', 	'respuesta'=>'Cicloserina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'60', 	'respuesta'=>'6 meses', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'60', 	'respuesta'=>'12 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'60', 	'respuesta'=>'9 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'60', 	'respuesta'=>'2 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'61', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'61', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'61', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'61', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'62', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'62', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'62', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'62', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'63', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'63', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'63', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'63', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'64', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'64', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'64', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'64', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'65', 	'respuesta'=>'Dar los medicamentos fraccionado en 3 tomas al día', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'65', 	'respuesta'=>'Dosificar correctamente a los fármacos antituberculosos', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'65', 	'respuesta'=>'Dar el tratamiento para que tome en casa cada semana', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'65', 	'respuesta'=>'Dar los medicamentos para todo el mes', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'66', 	'respuesta'=>'Pacientes contactos de MDR', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'66', 	'respuesta'=>'Pacientes que han concluido tratamiento para tuberculosis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'66', 	'respuesta'=>'Pacientes que no han recibido quimioprofilaxis desde hace 2 años', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'66', 	'respuesta'=>'Adultos y niños sin tuberculosis activa', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'67', 	'respuesta'=>'3 años', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'67', 	'respuesta'=>'6 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'67', 	'respuesta'=>'2 años', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'67', 	'respuesta'=>'1 año', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'68', 	'respuesta'=>'126mg/dl', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'68', 	'respuesta'=>'100 mg/dl', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'68', 	'respuesta'=>'80 mg/dl', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'68', 	'respuesta'=>'200 mg/dl', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'69', 	'respuesta'=>'Creatinian y perfil lipídico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'69', 	'respuesta'=>'Hemograma y Examen de orina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'69', 	'respuesta'=>'Grupo sanguíneo y coproparasitológico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'69', 	'respuesta'=>'Hemoglobina glicosilada y prueba de tolerancia a la glucosa', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'70', 	'respuesta'=>'0.7 a 1.3 mg/dL', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'70', 	'respuesta'=>'0,2 a 0.7 mg/dL', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'70', 	'respuesta'=>'2 a 4 mg/dL', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'70', 	'respuesta'=>'5 a 10 mg/dL', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'71', 	'respuesta'=>'Medidas de control administrativo y gerencial', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'71', 	'respuesta'=>'Medidas de control ambiental', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'71', 	'respuesta'=>'Medidas de protección respiratoria', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'71', 	'respuesta'=>'Medidas de saneamiento básico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'72', 	'respuesta'=>'Medidas de control administrativo y gerencial', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'72', 	'respuesta'=>'Medidas de control ambiental', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'72', 	'respuesta'=>'Medidas de protección respiratoria', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'72', 	'respuesta'=>'Medidas de saneamiento básico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'73', 	'respuesta'=>'Medidas de control administrativo y gerencial', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'73', 	'respuesta'=>'Medidas de control ambiental', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'73', 	'respuesta'=>'Medidas de protección respiratoria', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'73', 	'respuesta'=>'Medidas de saneamiento básico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'74', 	'respuesta'=>'1,5% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'74', 	'respuesta'=>'2% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'74', 	'respuesta'=>'2,5% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'74', 	'respuesta'=>'1% de la población total', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'75', 	'respuesta'=>'1,5% de la población total', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'75', 	'respuesta'=>'2% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'75', 	'respuesta'=>'2,5% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'75', 	'respuesta'=>'1% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'76', 	'respuesta'=>'1,5% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'76', 	'respuesta'=>'2% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'76', 	'respuesta'=>'2,5% de la población total', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'76', 	'respuesta'=>'1% de la población total', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'77', 	'respuesta'=>'Capacitar permanentemente al personal de salud y mejorar su desempeño', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'77', 	'respuesta'=>'Dar llamadas de atención por escrito', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'77', 	'respuesta'=>'Motivar al trabajador para el desarrollo laboral', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'77', 	'respuesta'=>'Retroalimentar al equipo de trabajo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'78', 	'respuesta'=>'Casos antiguos de una determinada enfermedad en un periodo de tiempo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'78', 	'respuesta'=>'Casos nuevos y antiguos de una determinada enfermedad en un periodo de tiempo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'78', 	'respuesta'=>'Casos nuevos de una determinada enfermedad en un periodo de tiempo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'78', 	'respuesta'=>'Ninguno', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'79', 	'respuesta'=>'Casos antiguos de una determinada enfermedad en un periodo de tiempo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'79', 	'respuesta'=>'Casos nuevos y antiguos de una determinada enfermedad en un periodo de tiempo', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'79', 	'respuesta'=>'Casos nuevos de una determinada enfermedad en un periodo de tiempo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'79', 	'respuesta'=>'Ninguno', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'80', 	'respuesta'=>'70%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'80', 	'respuesta'=>'100%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'80', 	'respuesta'=>'90%', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'80', 	'respuesta'=>'50%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'81', 	'respuesta'=>'Igual o mayor a 85%', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'81', 	'respuesta'=>'100%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'81', 	'respuesta'=>'50%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'81', 	'respuesta'=>'70%', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'82', 	'respuesta'=>'1%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'82', 	'respuesta'=>'10%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'82', 	'respuesta'=>'menos del 3%', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'82', 	'respuesta'=>'5%', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'83', 	'respuesta'=>'Debe recogerse antes de la toma de medicamentos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'83', 	'respuesta'=>'Recolectar en ambientes cerrados como el baño del hospital', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'83', 	'respuesta'=>'Debe ser de 3 a 5 ml y ser espesa y mucoide', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'83', 	'respuesta'=>'Identificar el envase con los datos personales del paciente', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'84', 	'respuesta'=>'A 8°C', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'84', 	'respuesta'=>'A 4°C', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'84', 	'respuesta'=>'A 0°C', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'84', 	'respuesta'=>'A 2°C', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'85', 	'respuesta'=>'En una conservadora de plastoformo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'85', 	'respuesta'=>'En un termo de vacuna', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'85', 	'respuesta'=>'Solo en el vaso recolector', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'85', 	'respuesta'=>'Con un sistema de triple embalaje', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'86', 	'respuesta'=>'Muestras no rotuladas o sin identificación', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'86', 	'respuesta'=>'Demora prolongada en el envío de la muestra al laboratorio', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'86', 	'respuesta'=>'Muestra derramada o con rotura de envase', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'86', 	'respuesta'=>'Muestra adecuadamente transportada en sistema de triple embalaje', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'87', 	'respuesta'=>'Rifampicina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'87', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'87', 	'respuesta'=>'Etambutol', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'87', 	'respuesta'=>'Pirazinamida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'88', 	'respuesta'=>'Cicloserina', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'88', 	'respuesta'=>'Amikacina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'88', 	'respuesta'=>'Levofloxacina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'88', 	'respuesta'=>'Amoxicilina más acido clavulánico', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'89', 	'respuesta'=>'12 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'89', 	'respuesta'=>'6 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'89', 	'respuesta'=>'9 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'89', 	'respuesta'=>'18 meses', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'90', 	'respuesta'=>'Cultivo   ', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'90', 	'respuesta'=>'Genexpert', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'90', 	'respuesta'=>'Baciloscopía', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'90', 	'respuesta'=>'Biopsia', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'91', 	'respuesta'=>'Tratamiento estrictamente supervisado', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'91', 	'respuesta'=>'Desensibilización', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'91', 	'respuesta'=>'Desintoxicación', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'91', 	'respuesta'=>'Restauración de medicamentos antituberculosos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'92', 	'respuesta'=>'Tuberculosis meningea  ', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'92', 	'respuesta'=>'Tuberculosis pulmonar   ', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'92', 	'respuesta'=>'Tuberculosis renal', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'92', 	'respuesta'=>'Tuberculosis ganglionar', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'93', 	'respuesta'=>'Periodo con síntomas de Vih-Sida', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'93', 	'respuesta'=>'Etapa de una enfermedad en la que más se manifiestan los síntomas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'93', 	'respuesta'=>'Intervalo entre el inicio de infección y la aparición de anticuerpos detectables', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'93', 	'respuesta'=>'Periodo con mucha viremia en el paciente', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'94', 	'respuesta'=>'Sindrome de emaciación por VIH', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'94', 	'respuesta'=>'Neumonía bacteriana recurrente', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'94', 	'respuesta'=>'Candidiasis esofágica', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'94', 	'respuesta'=>'Niveles de CD4 dentro de parámetros normales', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'95', 	'respuesta'=>'2 años', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'95', 	'respuesta'=>'6 meses', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'95', 	'respuesta'=>'1 año', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'95', 	'respuesta'=>'5 años', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'96', 	'respuesta'=>'Alcohol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'96', 	'respuesta'=>'Ketoconazol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'96', 	'respuesta'=>'Paracetamol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'96', 	'respuesta'=>'Antiácidos', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'97', 	'respuesta'=>'Antiácidos', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'97', 	'respuesta'=>'Paracetamol', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'97', 	'respuesta'=>'Carbamacepina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'97', 	'respuesta'=>'Ketoconazol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'98', 	'respuesta'=>'En todos los pacientes con coinfección TB/VIH, indistintamente de sus niveles de CD4 y hasta que la tuberculosis haya curado', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'98', 	'respuesta'=>'Sólo en los pacientes co tuberculosis que padecen de diarreas frecuentes', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'98', 	'respuesta'=>'Sólo en aquellos pacientes que tienen fiebre', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'98', 	'respuesta'=>'En pacientes que tienen candidiasis', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'99', 	'respuesta'=>'Recuento de CD4 bajo', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'99', 	'respuesta'=>'Fuerte respuesta al tratamiento antiretroviral', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'99', 	'respuesta'=>'Presencia de antígenos patógenos oportunistas', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'99', 	'respuesta'=>'Dosificación adecuada de los medicamentos antituberculosos', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'100', 	'respuesta'=>'Clorfeniramina', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'100', 	'respuesta'=>'Prednisona', 	'escorrecta'=>'1', 	]);
        Respuesta::create([	'pregunta_id'=>'100', 	'respuesta'=>'Cotrimoxazol', 	'escorrecta'=>'0', 	]);
        Respuesta::create([	'pregunta_id'=>'100', 	'respuesta'=>'Isoniacida', 	'escorrecta'=>'0', 	]);


        /*for ($i=101; $i <= 150 ; $i++) {
            # code...
            factory(Respuesta::class, 1)->create(['pregunta_id' => $i, 'escorrecta' => 1]);
            factory(Respuesta::class, 3)->create(['pregunta_id' => $i, 'escorrecta' => 0]);
        }*/
    }
}
